import "./globals.css";
import { Metadata, Viewport } from "next";
import Script from "next/script";
import { Toaster } from "@/components/ui/toast/toast";
import ModalRender from "@/components/modal/ModalRender";
import { ClientProvider, QueryProvider, AuthProvider } from "@/providers";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "Noonchi.ai",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Noonchi.ai",
  },
  icons: {
    apple: "/icons/icon-180.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head></head>
      <body className="min-h-dvh w-full">
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}');
          `}
        </Script>
        <AuthProvider>
          <QueryProvider>
            <ClientProvider>
              <div className="flex h-full min-h-dvh w-full justify-center">
                <div className="max-w-150 bg-gradient-primary w-full md:shadow-xl">
                  {children}
                </div>
              </div>
              <Toaster />
              <ModalRender />
            </ClientProvider>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
