import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Metadata } from "next";
import Script from "next/script";
import { Toaster } from "@/components/ui/toast/toast";
import ModalRender from "@/components/modal/ModalRender";
import { ClientProvider, QueryProvider, AuthProvider } from "@/providers";
export const metadata: Metadata = {
  title: "Noonchi.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head></head>
      <body className="min-h-screen w-full">
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-BJ45G5B4PZ"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-BJ45G5B4PZ');
          `}
        </Script>
        <AuthProvider>
          <QueryProvider>
            <ClientProvider>
              <div className="min-h-screen w-full md:flex md:justify-center">
                <div className="md:max-w-93.75 bg-gradient-primary w-full md:shadow-xl">
                  {children}
                </div>
              </div>
              <Toaster />
              <ModalRender />
            </ClientProvider>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
